
GET http://localhost:3000/api/notifications/7
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MjAsImxvZ2luIjoia2hhZGlqYUBnbWFpbC5jb20iLCJyb2xlIjoiQk9VVElRVUlFUiIsInByZW5vbSI6IktoYWRpamEiLCJub20iOiJCYSIsImNsaWVudElkIjo5LCJpYXQiOjE3Mjc4ODQ2NDgsImV4cCI6MTcyNzk3MTA0OH0.pTY4EZwxy38Arm2XM5IC3yb4Qo0yvFSfq6yFVPG7-NU